services:
  app:
    build:
      context: .
      target: runner

    environment:
      PORT: 8000 # for some reason nextjs will not use exposed port 8000 unless specified in the environment variables
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - app-network

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    command: tunnel --no-autoupdate run
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
